### ISSUE TITLE
This report is not supported in your REDCap version

### ISSUE THREAD

**Issue by eaneuhaus** [vanderbilt-redcap/analytics-module#1]
After installing the module and adding it to a project, the report page reads as follows:

> test - Analytics
> 
> The Analytics module automatically logs various user actions and displays them here, along with logs from other modules. We will likely expand this reporting capability in the future. Suggestions are always welcome.
> 
> This report is not supported in your REDCap version.

I'm on REDCap v8.7.2.

**Comment by mmcev106** [comment]
It looks like the module API changes required for this report to function have not made it into a REDCap release yet.  The last couple of releases look like they focused on bug fixes.  I would expect this report to work in the next "new feature" release (likely 8.8.0).  I'll go ahead and close this, but feel free to re-open it if you have any more questions.
